### ISSUE TITLE
Error on evaluation with COMET

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-evaluation#21]
CI: https://app.circleci.com/pipelines/github/mozilla/firefox-translations-models/217/workflows/9f30da93-bf18-4046-85fb-b9c741dfd0e7/jobs/217

I can also reproduce it locally. It seems the issue is related the update of the transient dependencies (transformers, pytorch, transformers-hub). We should upgrade the comet lib to the latest version and pin the critical dependencies.
This is the comet lib: https://github.com/Unbabel/COMET
```
[2023-07-28 22:19:50] [memory] Reserving 8 MB, device cpu0
Global seed set to 12
wmt20-comet-da is already in cache.
Created a temporary directory at /tmp/tmpz48ebwc7
Writing /tmp/tmpz48ebwc7/_remote_module_non_scriptable.py
Encoder model frozen.
Traceback (most recent call last):
  File "/usr/local/bin/comet-score", line 8, in <module>
    sys.exit(score_command())
  File "/usr/local/lib/python3.8/dist-packages/comet/cli/score.py", line 177, in score_command
    model = load_from_checkpoint(model_path)
  File "/usr/local/lib/python3.8/dist-packages/comet/models/__init__.py", line 66, in load_from_checkpoint
    model = model_class.load_from_checkpoint(checkpoint_path, **hparams)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/saving.py", line 209, in _load_model_state
    keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RegressionMetric:
	Unexpected key(s) in state_dict: "encoder.model.embeddings.position_ids". 

Traceback (most recent call last):
  File "eval/evaluate.py", line 146, in evaluate
    float_res = float(res.stdout.decode('utf-8').strip().split("\n")[-1])
ValueError: could not convert string to float: 'In all cases, you must book with the airline directly by telephone.'
Traceback (most recent call last):
  File "eval/evaluate.py", line 391, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "eval/evaluate.py", line 384, in run
    run_dir(lang_pairs, skip_existing, translators, evaluation_engine, gpus, models_dir=models_dir, results_dir=results_dir)
  File "eval/evaluate.py", line 182, in run_dir
    score = evaluate(pair, dataset_name, translator, evaluation_engine, gpus, results_dir=results_dir, models_dir=models_dir)
  File "eval/evaluate.py", line 146, in evaluate
    float_res = float(res.stdout.decode('utf-8').strip().split("\n")[-1])
ValueError: could not convert string to float: 'In all cases, you must book with the airline directly by telephone.'

Exited with code exit status 1

```

**Comment by eu9ene** [comment]
It blocks https://github.com/mozilla/firefox-translations-models/pull/78. I tried to update the Comet lib but it seems it conflicts with other packages and I see a new error. @nordzilla @gregtatum feel free to take a look at this one when you have time. It's a good opportunity to familiarize yourself with the evaluation part.
